name: CI/CD Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Git Checkout 
        uses: actions/checkout@v4

      - name: Set Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Echo pwd
        run: pwd

      - name: Build with Gradle
        run: ./gradlew build -x test --stacktrace

      - name: Build Docker Image
        run: docker build -t localhost:5000/gha-test:latest .

      - name: Push Docker Image
        run: docker push localhost:5000/gha-test:latest

      - name: Access to Target Server
        run: |
          ssh 73
          ls
