name: CI/CD Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Git Checkout 
        uses: actions/checkout@v4

      - name: Set Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=192.168.2.69 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=192.168.2.69 -Dhttps.proxyPort=3128" ./gradlew build -x test
